openapi: 3.0.3
info:
  title: Users Service
  version: 1.2.0
servers:
  - url: https://api.example.com/users
paths:
  /users:
    get:
      operationId: listUsers
      summary: List users
      description: Returns a paginated list of users.
      responses:
        '200':
          description: OK
  /users/{id}:
    get:
      operationId: getUser
      summary: Get user
      description: Retrieve a single user by id.
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          description: OK
components:
  schemas:
    User:
      type: object
      properties:
        id: { type: string }
        email: { type: string }
